# Generated by Django 2.2.6 on 2019-11-07 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='whiteboard',
            name='user',
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
