# Generated by Django 2.2.6 on 2019-12-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191107_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteboard',
            name='whiteboard_key',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
