# Generated by Django 2.2.6 on 2019-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_whiteboard_whiteboard_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteboard',
            name='whiteboard_key',
            field=models.IntegerField(),
        ),
    ]
