# Generated by Django 2.2.6 on 2019-12-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191203_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiteboard',
            name='user',
        ),
    ]
