# Generated by Django 2.2.6 on 2019-12-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191209_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
